### ISSUE TITLE
Is it good for film audio? What does the output means

### ISSUE THREAD

**Issue by ls-milkyway** [akinori-ito/peaqb-fast#2]
Can I use this to compare 2 audio encodes derived from the original source ...say a bluray disc...with stereo or 5.1 channel audio.?
Whar does the output:

`frame: 1
BandwidthRefb: 787
BandwidthTestb: 646.5
TotalNMRb -19.5803
WinModDiff1b: 0
ADBb: 0
EHSb: 0.231185
AvgModDiff1b: 0
AvgModDiff2b 0
RmsNoiseLoudb: 0
MFPDb: 0.00202244
RelDistFramesb: 0
DI: 2.89072
ODG: -0.000979518`

signifies?? I mean which values should be low & which should be high for test file to be as close as to the reference file???

**Comment by akinori-ito** [comment]
Yes you can. The output shows the variables for evaluating the audio, but only the ODG (the last column) is useful. Please refer to the Wikipedia:
https://en.wikipedia.org/wiki/Objective_difference_grade
